# $schema="https://gitlab.com/lanastara_foss/starship-jj/-/raw/main/schema.json?ref_type=heads"

module_separator = " "
reset_color = true

[bookmarks]
search_depth = 100
exclude = []

[[module]]
type = "Symbol"
symbol = "󱗆"
color = "Blue"

[[module]]
type = "Bookmarks"
separator = " "
color = "Magenta"
behind_symbol = "⇡"
surround_with_quotes = true
max_length = 20

[[module]]
type = "Commit"
max_length = 20
empty_text = "(no desc)"
surround_with_quotes = true

[[module]]
type = "State"
separator = " "

[module.conflict]
disabled = false
text = "(conflict)"
color = "Red"

[module.divergent]
disabled = false
text = "(divergent)"
color = "Cyan"

[module.empty]
disabled = true
text = "(empty)"
color = "Yellow"

[module.immutable]
disabled = true
text = "(immutable)"
color = "Yellow"

[module.hidden]
disabled = true
text = "(hidden)"
color = "Yellow"

[[module]]
type = "Metrics"
template = "[{changed} {added}{removed}]"
color = "Magenta"

[module.changed_files]
prefix = ""
suffix = ""
color = "Cyan"

[module.added_lines]
prefix = "+"
suffix = ""
color = "Green"

[module.removed_lines]
prefix = "-"
suffix = ""
color = "Red"

