---
database_file: /home/kalle/.local/share/timetrap/timetrap.db
round_in_seconds: 900
append_notes_delimiter: " "
formatter_search_paths:
- /home/kalle/.local/share/timetrap/timetrap_formatters/formatters
default_formatter: fraction
auto_sheet: default
auto_sheet_search_paths:
- "/home/kalle/.local/share/timetrap/auto_sheets"
default_command: 
auto_checkout: true
require_note: false
note_editor: false
week_start: Monday
