#! /bin/bash

LINUX_GIT='/bin/git'
WINDOWS_GIT='cmd.exe /c git'
: ${USE_GIT:=}

if [ "$USE_GIT" == 'windows' ]; then
	echo -e "\e[90mgit:Force override by USE_GIT env to use Windows $WINDOWS_GIT\e[0m" >&2
	GIT="$WINDOWS_GIT"
elif [ "$USE_GIT" == 'linux' ]; then
	echo -e "\e[90mgit:Force override by USE_GIT env to use Linux $LINUX_GIT\e[0m" >&2
	GIT="$LINUX_GIT"
else
	WORKING_DIR="$(pwd)"

	if [[ "${WORKING_DIR:0:3}" == '/c/' ]]; then
		GIT="$WINDOWS_GIT"
	else
		GIT="$LINUX_GIT"
	fi
fi

$GIT "$@"
