#!/bin/sh

# This file is called by River on login.
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

if ! cd "$(dirname "$0")"
then
    echo "river init: failed to change working directory to '$(dirname "$0")'" >&2
    exit 1
fi

export XDG_CURRENT_DESKTOP=river
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river

./keybinding.sh
./windows.sh
./theme.sh
./start-tools.sh

riverctl focus-follows-cursor normal
riverctl attach-mode bottom

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6
